### PR TITLE
Allow DictReader to accept a list of lines of input.

### LINKED ISSUE #1: DictReader has a different interface from csv.DictReader
The csv342 version of DictReader cannot accept a list of CSV lines, though the built in version in both Python 2 and Python 3 can do so. If you're interested in accepting patches, I could submit one for this issue.

## csv342 on python 2.7
```
>>> import csv342 as csv
>>> list(csv.DictReader(['a,b', '1,2']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 239, in next
    return self.__next__()
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 220, in __next__
    if self.fieldnames is None:
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 205, in fieldnames
    self._set_fieldnames_from_first_row()
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 199, in _set_fieldnames_from_first_row
    self._fieldnames = next(self.reader)
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 161, in next
    return self.__next__()
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 156, in __next__
    row = self.reader.next()
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 140, in next
    return self.__next__()
  File "/Users/lucaswiman/website/vendor/venv/lib/python2.7/site-packages/csv342.py", line 137, in __next__
    return self._text_stream.next().encode('utf-8')
AttributeError: 'list' object has no attribute 'next'
```

## Python 3.4 (also works on 3.6)
```
>>> import csv
>>> list(csv.DictReader(['a,b', '1,2']))
[{'a': '1', 'b': '2'}]
```

### PR DESCRIPTION
**Pull request by lucaswiman**
# Changes
Fixes #1, wherein `csv.DictReader` can read from a list of lines, but `csv342.DictReader` cannot. The fix here was to construct an `io.StringIO` instance containing the equivalent CSV text.

I also fixed an unrelated test failure, where the test asserted that StringIO.StringIO instances would not be accepted. This was failing for two reasons:
1. `StringIO` was being used as a context manager, which is not supported. This led to an `AttributeError`.
2. The code actually did accept `StringIO.StringIO` instances, which is problematic from the perspective of 2/3 compatibility. `StringIO.StringIO` switches types depending on what data is put into it, and so cannot provide an equivalent interface to Python 3. It also makes sense to force users of this library to only use the python-3-compatible `io.StringIO` buffer.

# Testing

I added a test case reproducing the failure described in #1, and verified that it fails. It passes after 6f4e79cfa081136e5308229df0232cef18f7fd5d. I also verified that the whole test suite now passes on Python 2.

# Thanks!

This library looks to be a great way of managing the upgrade to Python 3. Inconsistencies of the CSV packages between the two versions had made writing compatible code very difficult in an application I'm working on, so `csv342` is a great fit. Thanks for writing this library!

### CODE REVIEW

File: csv342.py [hunk 1]
```diff
@@ -127,6 +127,8 @@ class _Utf8Recoder(object):
         Iterator that reads a text stream and reencodes the input to UTF-8.
         """
         def __init__(self, text_stream):
+            if isinstance(text_stream, StringIO.StringIO):
+                raise Error('Cannot read from StringIO.StringIO instances.')
```
Comment (roskakori) [inline csv342.py]: If I understand your comment correctly, reading from `io.StringIO` would work. If so, the error message should state this (instead of stating was does not work):
```python
raise Error('StringIO.StringIO must be changed to io.StringIO in order to read a CSV from it')

File: test/test_csv342.py [hunk 2]
```diff
@@ -95,8 +95,8 @@ def test_can_read_from_StringIO(self):
     def test_fails_on_obsolete_StringIO(self):
         if csv.IS_PYTHON2:
             import StringIO
-            with StringIO.StringIO('a') as csv_stream:
-                self.assertRaises(csv.Error, csv.reader, csv_stream)
+            csv_stream = StringIO.StringIO('a')
+            self.assertRaises(csv.Error, csv.reader, csv_stream)
```
Comment (roskakori) [inline test/test_csv342.py:99]: This causes a minor resource leak. Wrap it in a `try: ... finally: csv_stream.close()`.

**Comment by lucaswiman** [comment]
It seems `csv.reader` also accepts a list of lines of input, so I'll need to make some additional changes.

**Comment by lucaswiman** [comment]
OK, I updated this to a more general fix that works for both `reader` and `DictReader`. The tests still pass on both Python 2.7 and Python 3.6.

**Review by roskakori — APPROVED** [review]

**Comment by nickpell** [comment]
Are there plans to make a new pypi release with this change included?

**Comment by roskakori** [comment]
@nickpell Version 1.0.0 is now available from PyPI. Thanks for the reminder.
